routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/





// ADMIN

// ADMIN LOGIN-LOGOUT-DASHBOARD

Route::get('/admin/manage', 'HomeController@indexAdmin')->name('adminIndex'); // dashboard


// ADMIN SCHOOL

//handle search routing (chaging search keyword from POST into url)
Route::post('/admin/manage/schools/search', 'SupportController@searchSchoolAdmin')
    ->name('adminSchoolSearchRedirect')
    ->middleware('auth.is_admin');
//handle search pagination
Route::get('/admin/manage/schools/search/{keyword}/page/{page_number}', 'Admin\\SchoolsController@search')
    ->name('adminSchoolSearch')
    ->middleware('auth.is_admin');
Route::get('/admin/manage/schools/logprestige', 'Admin\\SchoolsController@logPrestige')
    ->name('adminSchoolLogPrestige')
    ->middleware('auth.is_admin');
Route::get('/admin/manage/schools/page/{page_number}', 'Admin\\SchoolsController@indexPaginated')
    ->name('adminSchoolIndexPaginated')
    ->middleware('auth.is_admin');
Route::resource('/admin/manage/schools', 'Admin\\SchoolsController')
    ->middleware('auth.is_admin'); // CRUD resource controller
//->middleware('auth') // artinya hanya yang login yang bisa akses, tapi belum di cek apakah dia admin atau bukan

// ADMIN STUDENT
Route::post('/admin/manage/students/search', 'SupportController@searchStudentAdmin')
    ->name('adminStudentSearchRedirect')
    ->middleware('auth.is_admin');
Route::get('/admin/manage/students/search/{keyword}/page/{page_number}', 'Admin\\StudentsController@search')
    ->name('adminStudentSearch')
    ->middleware('auth.is_admin');
Route::get('/admin/manage/students/page/{page_number}', 'Admin\\StudentsController@indexPaginated')
    ->name('adminStudentIndexPaginated')
    ->middleware('auth.is_admin');
Route::resource('/admin/manage/students', 'Admin\\StudentsController')
    ->middleware('auth.is_admin'); // CRUD resource controller
//->middleware('auth.is_admin') // artinya hanya yang login sebagai admin yang bisa akses,
//cara buat middleware:
// php artisan make:middleware CheckUserIsAdmin
// contoh middleware seperti di 'App\Http\Middleware\CheckUserIsAdmin.php' dan
// registerkan middleware tersebut di 'App\Http\Kernel.php' pada bagian $routeMiddleware

// ADMIN SUBJECTS
Route::post('/admin/manage/subjects/search', 'SupportController@searchSubjectAdmin')
    ->name('adminSubjectSearchRedirect')
    ->middleware('auth.is_admin');
Route::get('/admin/manage/subjects/search/{keyword}/page/{page_number}', 'Admin\\SubjectsController@search')
    ->name('adminSubjectSearch')
    ->middleware('auth.is_admin');
Route::get('/admin/manage/subjects/page/{page_number}', 'Admin\\SubjectsController@indexPaginated')
    ->name('adminSubjectIndexPaginated')
    ->middleware('auth.is_admin');
Route::resource('/admin/manage/subjects', 'Admin\\SubjectsController')
    ->middleware('auth.is_admin'); // CRUD resource controller

// ADMIN TESTS
Route::post('/admin/manage/tests/search', 'SupportController@searchTestAdmin')
    ->name('adminTestSearchRedirect')
    ->middleware('auth.is_admin');
Route::get('/admin/manage/tests/search/{keyword}/page/{page_number}', 'Admin\\TestsController@search')
    ->name('adminTestSearch')
    ->middleware('auth.is_admin');
Route::post('/admin/manage/tests/{id}/validasinilai', 'Admin\\TestsController@validasiNilai')
    ->name('adminTestValidasiNilai')
    ->middleware('auth.is_admin');
Route::get('/admin/manage/tests/page/{page_number}', 'Admin\\TestsController@indexPaginated')
    ->name('adminTestIndexPaginated')
    ->middleware('auth.is_admin');
Route::resource('/admin/manage/tests', 'Admin\\TestsController')
    ->middleware('auth.is_admin'); // CRUD resource controller

// ADMIN MASTER APPRENTICE
Route::get('/admin/manage/master_apprentice', 'Admin\\MasterApprenticeController@index')
    ->name('masapp.index')
    ->middleware('auth.is_admin'); // CRUD index manual
Route::post('/admin/manage/master_apprentice/search', 'SupportController@searchMasterApprenticeAdmin')
    ->name('adminMasAppSearchRedirect')
    ->middleware('auth.is_admin');
Route::get('/admin/manage/master_apprentice/search/{keyword}/page/{page_number}', 'Admin\\MasterApprenticeController@search')
    ->name('adminMasAppSearch')
    ->middleware('auth.is_admin');
Route::get('/admin/manage/master_apprentice/page/{page_number}', 'Admin\\MasterApprenticeController@indexPaginated')
    ->name('adminMasAppIndexPaginated')
    ->middleware('auth.is_admin');
Route::get('/admin/manage/master_apprentice/{master_student_id}/{apprentice_student_id}/{subject_id}/edit', 'Admin\\MasterApprenticeController@edit')
    ->name('masapp.edit')
    ->middleware('auth.is_admin'); // CRUD edit manual
Route::put('/admin/manage/master_apprentice/{master_student_id}/{apprentice_student_id}/{subject_id}', 'Admin\\MasterApprenticeController@update')
    ->name('masapp.update')
    ->middleware('auth.is_admin'); // CRUD update manual
Route::get('/admin/manage/master_apprentice/create', 'Admin\\MasterApprenticeController@create')
    ->name('masapp.create')
    ->middleware('auth.is_admin'); // CRUD create manual
Route::post('/admin/manage/master_apprentice', 'Admin\\MasterApprenticeController@store')
    ->name('masapp.store')
    ->middleware('auth.is_admin'); // CRUD store manual
Route::delete('/admin/manage/master_apprentice/{master_student_id}/{apprentice_student_id}/{subject_id}', 'Admin\\MasterApprenticeController@destroy')
    ->name('masapp.destroy')
    ->middleware('auth.is_admin'); // CRUD delete manual
// Route::resource('/admin/manage/master_apprentice', 'Admin\\MasterApprenticeController'); // CRUD resource controller



// PUBLIC RANK

// RANK STUDENTS
Route::get('/rank', 'StudentRankPagesController@rankGlobalIndex')
    ->name('publicStudentIndex'); // suruh redirect ke /rank/page/1 !!
Route::get('/rank/page/{page_number}', 'StudentRankPagesController@rankGlobal')
    ->name('publicStudentIndexPaginated'); // keseluruhan / global
Route::get('/rank/level/{level_jenjang}/page/{page_number}', 'StudentRankPagesController@rankLevel'); // di jenjang yang sama (SD saja, atau SMP saja, atau SMA saja)

Route::post('student/search', 'SupportController@searchStudentPublic')
    ->name('publicStudentSearchProcess');
Route::get('/student/search/{keyword}/page/{page_number}', 'StudentRankPagesController@search')
    ->name('publicStudentSearch'); // search
Route::get('/student/{id}', 'StudentRankPagesController@profile')
    ->name('publicStudentProfile'); // profile

// RANK SCHOOLS
Route::get('/rank/schools', 'SchoolRankPagesController@rankGlobalIndex')
    ->name('publicSchoolIndex'); // suruh redirect ke /rank/schools/page/1 !!
Route::get('/rank/schools/page/{page_number}', 'SchoolRankPagesController@rankGlobal')
    ->name('publicSchoolIndexPaginated'); // keseluruhan / global
Route::get('/rank/schools/level/{level_jenjang}/page/{page_number}', 'SchoolRankPagesController@rankLevel'); // di kota yang sama

Route::post('school/search', 'SupportController@searchSchoolPublic')
    ->name('publicSchoolSearchProcess');
Route::get('/school/search/{keyword}/page/{page_number}', 'SchoolRankPagesController@search')
    ->name('publicSchoolSearch'); // search
Route::get('/school/{id}', 'SchoolRankPagesController@profile')
    ->name('publicSchoolProfile'); // profile



// STUDENT MEMBER MASTER-APPRENTICE PROPOSAL
Route::get('/masapp', 'MemberProposalController@landing') // display 2 choice, discover master, discover apprentice, notif (dari proposals)
    ->name('memberMasappLanding')
    ->middleware('auth.is_student');
Route::get('/masapp/discover/{arg_master_or_apprentice}', 'MemberProposalController@discover') // display map and table
    ->name('memberMasappDiscover')
    ->middleware('auth.is_student');
Route::get('/masapp/discover/{arg_master_or_apprentice}/{subject_id}', 'MemberProposalController@discover') // display map and table
    ->name('memberMasappSubject')
    ->middleware('auth.is_student');
Route::post('/masapp/discover', 'MemberProposalController@searchRedirect') // display map and table
    ->name('memberMasappDiscoverSearchRedirect')
    ->middleware('auth.is_student');

Route::get('/masapp/apply/{arg_master_or_apprentice}/{target_student_id}/{subject_id}', 'MemberProposalController@applyForm')
    ->name('memberMasappApplyForm')
    ->middleware('auth.is_student');
Route::post('/masapp/apply', 'MemberProposalController@applyProcess')
    ->name('memberMasappApplyProcess')
    ->middleware('auth.is_student');

Route::get('/masapp/proposals', 'MemberProposalController@proposals')
    ->name('memberMasappProposals')
    ->middleware('auth.is_student');
Route::post('/masapp/proposals/{proposal_id}/{arg_accept_or_decline}', 'MemberProposalController@respond')
    ->name('memberMasappRespond')
    ->middleware('auth.is_student');



// LOGIN PAGE
//Route::get('/', 'PagesController@indexPublic')->name('#');
/*
Route::get('/login', 'PagesController@loginPublic');
Route::post('/login', 'PagesController@loginPublicProcess');
Route::get('/logout', 'PagesController@logoutPublic');
*/

// OLD, DEPRECATED, FOR HACKATHON DEMO
/*
Route::get('/', 'PagesController@loginPage');
Route::get('/login', 'PagesController@loginPage');

Route::get('/table_students', 'PagesController@listStudentsSimple');
Route::get('/students', 'PagesController@listStudents');
Route::get('/admin_students', 'PagesController@listStudentsAdmin');
Route::get('/student/{student_id}', 'PagesController@studentDetail');
Route::get('/discover', 'PagesController@googleMaps');
Route::get('/dashboard', 'PagesController@dashboard');
Route::get('/schools', 'PagesController@listSchools');

app/Subject.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Exception;

class Subject extends Model
{
    protected $table = 'subjects';
    public $timestamps = true;
    protected $primaryKey = 'id';
    //protected $keyType = 'integer';

    // relationships
    public function tests()
    {
        return $this->hasMany('App\Test');
    }

    public function masterApprentices()
    {
        return $this->hasMany('App\MasterApprentice');
    }

    // other methods
    public function isCanBeDeleted()
    {
        $jumlahTest = Test::where('subject_id', $this->id)->count();
        if($jumlahTest == 0)
        {
            return true;
        }
        else
        {
            return false;
        }
    }
}

app/Http/Controllers/Admin/SubjectsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Config;
use App\Subject;
use App\Http\Requests\AdminSubjectFormRequest;

class SubjectsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return redirect(route('adminSubjectIndexPaginated', ['page_number' => 1]));
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function indexPaginated($page_number)
    {
        return $this->search(null, $page_number);
    }

    public function search($keyword, $page_number)
    {
        $query = null;
        if($keyword == null)
        {
            $query = Subject::all();
        }
        else
        {
            $query = Subject::where('nama', 'like', '%' . $keyword . '%')
                ->orWhere('id', 'like', $keyword . '%')
                ->get();
        }

        $subjects = $query->forPage($page_number, Config::get('kristian.pagination_max_item'));
        $viewArgs["subjects"] = $subjects;

        $viewArgs["page"]["current"] = $page_number;
        $viewArgs["page"]["max"] = ceil($query->count() / Config::get('kristian.pagination_max_item'));
        if($viewArgs["page"]["max"] == 0) $viewArgs["page"]["max"] = 1;

        if($keyword != null && isset($keyword)) $viewArgs["keyword"] = $keyword;
        
        return view('admin.subject.list', $viewArgs);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $subject = new Subject();
        $subject->id = -1;

        $viewArgs["subject"] = $subject;
        return view('admin.subject.edit', $viewArgs);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AdminSubjectFormRequest $request)
    {
        try
        {
            $subject = new Subject();
            $subject->nama = $request->nama;
            $subject->singkatan = $request->singkatan;

            $subject->save();
            //return json_encode(['status' => 'success']);
            return redirect(route('subjects.edit', ['id' => $subject->id]));
        }
        catch (Exception $e)
        {
            return json_encode(['status' => 'failed', 'message' => $e->getMessage()]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $subject = Subject::find($id);

        $viewArgs["subject"] = $subject;
        return view('admin.subject.edit', $viewArgs);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(AdminSubjectFormRequest $request, $id)
    {
        try
        {
            $subject = Subject::find($id);
            $subject->nama = $request->nama;
            $subject->singkatan = $request->singkatan;

            $subject->save();
            //return json_encode(['status' => 'success']);
            return redirect(route('subjects.edit', ['id' => $id]));
        }
        catch (Exception $e)
        {
            return json_encode(['status' => 'failed', 'message' => $e->getMessage()]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try
        {
            $subject = Subject::find($id);

            $subject->delete();
            return json_encode(['status' => 'success']);
        }
        catch (Exception $e)
        {
            return json_encode(['status' => 'failed', 'message' => $e->getMessage()]);
        }
    }
}

resources/views/admin/subject/edit.blade.php
@extends('admin.subject.template')
@section('content')

  <div class="content">
    <div class="container-fluid">

      <div class="col-md-12">
        <div class="card">
          <div class="card-header card-header-primary">
            <h4 class="card-title">
              @if( $subject->id != -1 )
                Edit Subject
              @else
                Create New Subject
              @endif
            </h4>
            <p class="card-category">
              @if( $subject->id != -1 )
                ID: {{ $subject->id }}
              @endif
            </p>
          </div>
          <div class="card-body">
            @if( $subject->id != -1 )
              <form action="{{ route('subjects.update', ['id' => $subject->id]) }}" method="POST" enctype="multipart/form-data">
            @else
              <form action="{{ route('subjects.store') }}" method="POST" enctype="multipart/form-data">
            @endif

              @if( $subject->id != -1 )
                @method('PUT')
              @else
                @method('POST')
              @endif
              @csrf
              <div class="row">
                <div class="col-md-9">
                  <div class="form-group label-floating
                    @if($errors->has('nama'))
                      has-error
                    @endif">
                    <label class="bmd-label-floating">Nama</label>
                    <input type="text" class="form-control" name="nama" value="{{ $subject->nama }}">
                    @if($errors->has('nama'))
                      <span class="label-error">{{ $errors->first('nama') }}</span>
                    @endif
                  </div>
                </div>
                <div class="col-md-3">
                  <div class="form-group label-floating
                    @if($errors->has('singkatan'))
                      has-error
                    @endif">
                    <label class="bmd-label-floating">Singkatan</label>
                    <input type="text" class="form-control" name="singkatan" value="{{ $subject->singkatan }}">
                    @if($errors->has('singkatan'))
                      <span class="label-error">{{ $errors->first('singkatan') }}</span>
                    @endif
                  </div>
                </div>
              </div>
              <button type="submit" class="btn btn-primary pull-right">Save</button>
              <a href="{{ route('subjects.index') }}"><button type="button" class="btn btn-secondary pull-right">Cancel</button></a>
              <div class="clearfix"></div>
            </form>
          </div>
        </div>
      </div>

    </div>
  </div>

@endsection

resources/views/admin/subject/list.blade.php
@extends('admin.subject.template')
@section('content')
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <div class="card">
            <div class="card-header card-header-primary">
              <h4 class="card-title">
                Subjects
                <a class="btn btn-success" style="float: right;" href="{{ route('subjects.create') }}">
                  <i class="material-icons">add</i> Add New
                  <div class="ripple-container"></div>
                </a>
              </h4>
              <p class="card-category">Manage subjects</p>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table">
                  <thead class=" text-primary">
                    <th>ID</th>
                    <th>Nama</th>
                    <th>Singkatan</th>
                    <th>Action</th>
                  </thead>
                  <tbody>
                    @foreach($subjects as $row)
                      <tr>
                        <td>{{ $row->id }}</td>
                        <td>{{ $row->nama }}</td>
                        <td>{{ $row->singkatan }}</td>
                        <td>
                          <a href="{{ route('subjects.edit', ['id' => $row->id]) }}"><button class="btn-small btn-primary">Edit</button></a>
                          @if($row->isCanBeDeleted())
                            <button class="btn-small btn-danger" onclick="changeToDeleteId({{ $row->id }});" data-toggle="modal" data-target="#modal_delete">Delete</button>
                          @else
                            <button class="btn-small btn-secondary" disabled>Delete</button>
                          @endif
                        </td>
                      </tr>
                    @endforeach
                  </tbody>
                </table>
              </div>
              @include('common.addon_pagination')
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Modal -->
  <div class="modal fade" id="modal_delete" tabindex="-1" role="dialog" aria-labelledby="modal_delete_title" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="modal_delete_title">Delete</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          Are you sure you want to delete this data?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
          <button type="button" class="btn btn-danger" onclick="deleteItem();">Delete</button>
        </div>
      </div>
    </div>
  </div>
@endsection

@section('scripts')
  <script type="text/javascript">
    var toDeleteId = -1;
    function deleteItem()
    {
      var urlFormat = "{{ route('subjects.destroy', ['id' => 'VAR_ID']) }}";
      urlFormat = urlFormat.replace('VAR_ID', toDeleteId);
      //alert(urlFormat);
      $.ajax({
        type: "DELETE",
        url: urlFormat,
        headers: { "X-CSRF-TOKEN" : "{{ csrf_token() }}" },
        processData: false,
        contentType: false,
        cache: false,
        timeout: 600000,
        success: function (data)
        {
          varResultObj = JSON.parse(data); // assume the return will always be {"status" : "success"} OR {"status" : "fail"}
          if(varResultObj.status == "success")
          {
            window.location = "{{ route('subjects.index') }}";
          }
          else
          {
            alert('ERROR, response: ' + data);
          }
        },
        error: function (e) {
          alert('Cannot delete record, foreign key constraint failed!');
          console.log("ERROR : ", e);
        }
      });
    }
    function changeToDeleteId(newId)
    {
      toDeleteId = newId;
    }
  </script>
@endsection

resources/views/admin/subject/template.blade.php
@extends('admin.template')

@section('searchBarAction')
  {{ route('adminSubjectSearchRedirect') }}
@endsection

@section('searchBarVisibility')
  inline-block
@endsection

@section('scriptNav')
  <script type="text/javascript">
    $("#nav_item_subjects").addClass("active");
  </script>
@endsection