routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/





// ADMIN

// ADMIN LOGIN-LOGOUT-DASHBOARD

Route::get('/admin/manage', 'HomeController@indexAdmin')->name('adminIndex'); // dashboard


// ADMIN SCHOOL

//handle search routing (chaging search keyword from POST into url)
Route::post('/admin/manage/schools/search', 'SupportController@searchSchoolAdmin')
    ->name('adminSchoolSearchRedirect')
    ->middleware('auth.is_admin');
//handle search pagination
Route::get('/admin/manage/schools/search/{keyword}/page/{page_number}', 'Admin\\SchoolsController@search')
    ->name('adminSchoolSearch')
    ->middleware('auth.is_admin');
Route::get('/admin/manage/schools/logprestige', 'Admin\\SchoolsController@logPrestige')
    ->name('adminSchoolLogPrestige')
    ->middleware('auth.is_admin');
Route::get('/admin/manage/schools/page/{page_number}', 'Admin\\SchoolsController@indexPaginated')
    ->name('adminSchoolIndexPaginated')
    ->middleware('auth.is_admin');
Route::resource('/admin/manage/schools', 'Admin\\SchoolsController')
    ->middleware('auth.is_admin'); // CRUD resource controller
//->middleware('auth') // artinya hanya yang login yang bisa akses, tapi belum di cek apakah dia admin atau bukan

// ADMIN STUDENT
Route::post('/admin/manage/students/search', 'SupportController@searchStudentAdmin')
    ->name('adminStudentSearchRedirect')
    ->middleware('auth.is_admin');
Route::get('/admin/manage/students/search/{keyword}/page/{page_number}', 'Admin\\StudentsController@search')
    ->name('adminStudentSearch')
    ->middleware('auth.is_admin');
Route::get('/admin/manage/students/page/{page_number}', 'Admin\\StudentsController@indexPaginated')
    ->name('adminStudentIndexPaginated')
    ->middleware('auth.is_admin');
Route::resource('/admin/manage/students', 'Admin\\StudentsController')
    ->middleware('auth.is_admin'); // CRUD resource controller
//->middleware('auth.is_admin') // artinya hanya yang login sebagai admin yang bisa akses,
//cara buat middleware:
// php artisan make:middleware CheckUserIsAdmin
// contoh middleware seperti di 'App\Http\Middleware\CheckUserIsAdmin.php' dan
// registerkan middleware tersebut di 'App\Http\Kernel.php' pada bagian $routeMiddleware

// ADMIN SUBJECTS
Route::post('/admin/manage/subjects/search', 'SupportController@searchSubjectAdmin')
    ->name('adminSubjectSearchRedirect')
    ->middleware('auth.is_admin');
Route::get('/admin/manage/subjects/search/{keyword}/page/{page_number}', 'Admin\\SubjectsController@search')
    ->name('adminSubjectSearch')
    ->middleware('auth.is_admin');
Route::get('/admin/manage/subjects/page/{page_number}', 'Admin\\SubjectsController@indexPaginated')
    ->name('adminSubjectIndexPaginated')
    ->middleware('auth.is_admin');
Route::resource('/admin/manage/subjects', 'Admin\\SubjectsController')
    ->middleware('auth.is_admin'); // CRUD resource controller

// ADMIN TESTS
Route::post('/admin/manage/tests/search', 'SupportController@searchTestAdmin')
    ->name('adminTestSearchRedirect')
    ->middleware('auth.is_admin');
Route::get('/admin/manage/tests/search/{keyword}/page/{page_number}', 'Admin\\TestsController@search')
    ->name('adminTestSearch')
    ->middleware('auth.is_admin');
Route::post('/admin/manage/tests/{id}/validasinilai', 'Admin\\TestsController@validasiNilai')
    ->name('adminTestValidasiNilai')
    ->middleware('auth.is_admin');
Route::get('/admin/manage/tests/page/{page_number}', 'Admin\\TestsController@indexPaginated')
    ->name('adminTestIndexPaginated')
    ->middleware('auth.is_admin');
Route::resource('/admin/manage/tests', 'Admin\\TestsController')
    ->middleware('auth.is_admin'); // CRUD resource controller

// ADMIN MASTER APPRENTICE
Route::get('/admin/manage/master_apprentice', 'Admin\\MasterApprenticeController@index')
    ->name('masapp.index')
    ->middleware('auth.is_admin'); // CRUD index manual
Route::post('/admin/manage/master_apprentice/search', 'SupportController@searchMasterApprenticeAdmin')
    ->name('adminMasAppSearchRedirect')
    ->middleware('auth.is_admin');
Route::get('/admin/manage/master_apprentice/search/{keyword}/page/{page_number}', 'Admin\\MasterApprenticeController@search')
    ->name('adminMasAppSearch')
    ->middleware('auth.is_admin');
Route::get('/admin/manage/master_apprentice/page/{page_number}', 'Admin\\MasterApprenticeController@indexPaginated')
    ->name('adminMasAppIndexPaginated')
    ->middleware('auth.is_admin');
Route::get('/admin/manage/master_apprentice/{master_student_id}/{apprentice_student_id}/{subject_id}/edit', 'Admin\\MasterApprenticeController@edit')
    ->name('masapp.edit')
    ->middleware('auth.is_admin'); // CRUD edit manual
Route::put('/admin/manage/master_apprentice/{master_student_id}/{apprentice_student_id}/{subject_id}', 'Admin\\MasterApprenticeController@update')
    ->name('masapp.update')
    ->middleware('auth.is_admin'); // CRUD update manual
Route::get('/admin/manage/master_apprentice/create', 'Admin\\MasterApprenticeController@create')
    ->name('masapp.create')
    ->middleware('auth.is_admin'); // CRUD create manual
Route::post('/admin/manage/master_apprentice', 'Admin\\MasterApprenticeController@store')
    ->name('masapp.store')
    ->middleware('auth.is_admin'); // CRUD store manual
Route::delete('/admin/manage/master_apprentice/{master_student_id}/{apprentice_student_id}/{subject_id}', 'Admin\\MasterApprenticeController@destroy')
    ->name('masapp.destroy')
    ->middleware('auth.is_admin'); // CRUD delete manual
// Route::resource('/admin/manage/master_apprentice', 'Admin\\MasterApprenticeController'); // CRUD resource controller



// PUBLIC RANK

// RANK STUDENTS
Route::get('/rank', 'StudentRankPagesController@rankGlobalIndex')
    ->name('publicStudentIndex'); // suruh redirect ke /rank/page/1 !!
Route::get('/rank/page/{page_number}', 'StudentRankPagesController@rankGlobal')
    ->name('publicStudentIndexPaginated'); // keseluruhan / global
Route::get('/rank/level/{level_jenjang}/page/{page_number}', 'StudentRankPagesController@rankLevel'); // di jenjang yang sama (SD saja, atau SMP saja, atau SMA saja)

Route::post('student/search', 'SupportController@searchStudentPublic')
    ->name('publicStudentSearchProcess');
Route::get('/student/search/{keyword}/page/{page_number}', 'StudentRankPagesController@search')
    ->name('publicStudentSearch'); // search
Route::get('/student/{id}', 'StudentRankPagesController@profile')
    ->name('publicStudentProfile'); // profile

// RANK SCHOOLS
Route::get('/rank/schools', 'SchoolRankPagesController@rankGlobalIndex')
    ->name('publicSchoolIndex'); // suruh redirect ke /rank/schools/page/1 !!
Route::get('/rank/schools/page/{page_number}', 'SchoolRankPagesController@rankGlobal')
    ->name('publicSchoolIndexPaginated'); // keseluruhan / global
Route::get('/rank/schools/level/{level_jenjang}/page/{page_number}', 'SchoolRankPagesController@rankLevel'); // di kota yang sama

Route::post('school/search', 'SupportController@searchSchoolPublic')
    ->name('publicSchoolSearchProcess');
Route::get('/school/search/{keyword}/page/{page_number}', 'SchoolRankPagesController@search')
    ->name('publicSchoolSearch'); // search
Route::get('/school/{id}', 'SchoolRankPagesController@profile')
    ->name('publicSchoolProfile'); // profile



// STUDENT MEMBER MASTER-APPRENTICE PROPOSAL
Route::get('/masapp', 'MemberProposalController@landing') // display 2 choice, discover master, discover apprentice, notif (dari proposals)
    ->name('memberMasappLanding')
    ->middleware('auth.is_student');
Route::get('/masapp/discover/{arg_master_or_apprentice}', 'MemberProposalController@discover') // display map and table
    ->name('memberMasappDiscover')
    ->middleware('auth.is_student');
Route::get('/masapp/discover/{arg_master_or_apprentice}/{subject_id}', 'MemberProposalController@discover') // display map and table
    ->name('memberMasappSubject')
    ->middleware('auth.is_student');
Route::post('/masapp/discover', 'MemberProposalController@searchRedirect') // display map and table
    ->name('memberMasappDiscoverSearchRedirect')
    ->middleware('auth.is_student');

Route::get('/masapp/apply/{arg_master_or_apprentice}/{target_student_id}/{subject_id}', 'MemberProposalController@applyForm')
    ->name('memberMasappApplyForm')
    ->middleware('auth.is_student');
Route::post('/masapp/apply', 'MemberProposalController@applyProcess')
    ->name('memberMasappApplyProcess')
    ->middleware('auth.is_student');

Route::get('/masapp/proposals', 'MemberProposalController@proposals')
    ->name('memberMasappProposals')
    ->middleware('auth.is_student');
Route::post('/masapp/proposals/{proposal_id}/{arg_accept_or_decline}', 'MemberProposalController@respond')
    ->name('memberMasappRespond')
    ->middleware('auth.is_student');



// LOGIN PAGE
//Route::get('/', 'PagesController@indexPublic')->name('#');
/*
Route::get('/login', 'PagesController@loginPublic');
Route::post('/login', 'PagesController@loginPublicProcess');
Route::get('/logout', 'PagesController@logoutPublic');
*/

// OLD, DEPRECATED, FOR HACKATHON DEMO
/*
Route::get('/', 'PagesController@loginPage');
Route::get('/login', 'PagesController@loginPage');

Route::get('/table_students', 'PagesController@listStudentsSimple');
Route::get('/students', 'PagesController@listStudents');
Route::get('/admin_students', 'PagesController@listStudentsAdmin');
Route::get('/student/{student_id}', 'PagesController@studentDetail');
Route::get('/discover', 'PagesController@googleMaps');
Route::get('/dashboard', 'PagesController@dashboard');
Route::get('/schools', 'PagesController@listSchools');

app/Http/Controllers/Admin/SchoolsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use App\School;
use Config;
use App\Http\Requests\AdminSchoolFormRequest;

class SchoolsController extends Controller
{
    // need to be logged in as admin to continue
    public function __construct()
    {
        //$this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return redirect(route('adminSchoolIndexPaginated', ['page_number' => 1]));
    }

    /**
     * Display a listing of the resource with pagination.
     *
     * @return \Illuminate\Http\Response
     */
    public function indexPaginated($page_number)
    {
        return $this->search(null, $page_number);
    }

    public function search($keyword, $page_number)
    {
        $query = null;
        if($keyword == null)
        {
            $query = School::all();
        }
        else
        {
            $query = School::where('nama', 'like', '%' . $keyword . '%')
                ->orWhere('id', 'like', $keyword . '%')
                ->get();
        }

        $schools = $query->forPage($page_number, Config::get('kristian.pagination_max_item'));
        $viewArgs["schools"] = $schools;

        $viewArgs["page"]["current"] = $page_number;
        $viewArgs["page"]["max"] = ceil($query->count() / Config::get('kristian.pagination_max_item'));
        if($viewArgs["page"]["max"] == 0) $viewArgs["page"]["max"] = 1;

        if($keyword != null && isset($keyword)) $viewArgs["keyword"] = $keyword;
        
        return view('admin.school.list', $viewArgs);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $school = new School();
        $school->id = -1;

        $viewArgs["school"] = $school;
        return view('admin.school.edit', $viewArgs);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AdminSchoolFormRequest $request)
    {
        try
        {
            $school = new School();
            $school->id = $request->id;
            $school->nama = $request->nama;
            $school->alamat = $request->alamat;
            $school->status = $request->status;
            $school->jenjang = $request->jenjang;
            $school->prestige = $request->prestige;
            $school->level = $request->level;
            $school->x = $request->x;
            $school->y = $request->y;

            //handle picture upload
            if ($request->hasFile('picture'))
            {
                $picture = $request->file('picture');
                $destinationPath = base_path('public').'/img/schools/';
                $name = $school->id . '.' . $picture->getClientOriginalExtension();
                if (File::exists($destinationPath . $school->id . ".jpg"))
                {
                    File::delete($destinationPath . $school->id . ".jpg");
                }
                if (File::exists($destinationPath . $school->id . ".png"))
                {
                    File::delete($destinationPath . $school->id . ".png");
                }
                $picture->move($destinationPath, $name);
            }

            $school->save();
            //return json_encode(['status' => 'success']);
            return redirect(route('schools.edit', ['id' => $request->id]));
        }
        catch (Exception $e)
        {
            return json_encode(['status' => 'failed', 'message' => $e->getMessage()]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $schools = School::find($id); // dd($schools);
        $viewArgs["school"] = $schools;
        return view('admin.school.detail', $viewArgs);

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $schools = School::find($id);
        $viewArgs["school"] = $schools;
        return view('admin.school.edit', $viewArgs);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(AdminSchoolFormRequest $request, $id)
    {
        try
        {
            $school = School::find($id);
            $school->nama = $request->nama;
            $school->alamat = $request->alamat;
            $school->status = $request->status;
            $school->jenjang = $request->jenjang;
            $school->prestige = $request->prestige;
            $school->level = $request->level;
            $school->x = $request->x;
            $school->y = $request->y;

            if ($request->hasFile('picture'))
            {
                $picture = $request->file('picture');
                $destinationPath = base_path('public').'/img/schools/';
                $name = $school->id . '.' . $picture->getClientOriginalExtension();
                if (File::exists($destinationPath . $school->id . ".jpg"))
                {
                    File::delete($destinationPath . $school->id . ".jpg");
                }
                if (File::exists($destinationPath . $school->id . ".png"))
                {
                    File::delete($destinationPath . $school->id . ".png");
                }
                $picture->move($destinationPath, $name);
            }

            $school->save();
            //return json_encode(['status' => 'success']);
            return redirect(route('schools.edit', ['id' => $id]));
        }
        catch (Exception $e)
        {
            return json_encode(['status' => 'failed', 'message' => $e->getMessage()]);
        }




    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try
        {
            $school = School::find($id);

            $school->delete();
            return json_encode(['status' => 'success']);
        }
        catch (Exception $e)
        {
            return json_encode(['status' => 'failed', 'message' => $e->getMessage()]);
        }
    }





    public function logPrestige()
    {
        try
        {
            $schools = School::all();
            foreach ($schools as $key => $value)
            {
                $value->logPrestige();
            }
            return json_encode(['status' => 'success']);
        }
        catch (Exception $e)
        {
            return json_encode(['status' => 'failed', 'message' => $e->getMessage()]);
        }
    }
}

resources/views/admin/school/edit.blade.php
@extends('admin.school.template')
@section('content')

  <div class="content">
    <div class="container-fluid">

      <div class="col-md-12">
        <div class="card">
          <div class="card-header card-header-primary">
            <h4 class="card-title">
              @if( $school->id != -1 )
                Edit School
              @else
                Create New School
              @endif
            </h4>
            <p class="card-category">
              @if( $school->id != -1 )
                NPSN: {{ $school->id }}
              @endif
            </p>
          </div>
          <div class="card-body">
            @if( $school->id != -1 )
              <form action="{{ route('schools.update', ['id' => $school->id]) }}" method="POST" enctype="multipart/form-data">
            @else
              <form action="{{ route('schools.store') }}" method="POST" enctype="multipart/form-data">
            @endif

              @if( $school->id != -1 )
                @method('PUT')
              @else
                @method('POST')
                <div class="row">
                  <div class="col-md-12">
                    <div class="form-group label-floating
                    @if($errors->has('id'))
                      has-error
                    @endif">
                      <label class="bmd-label-floating">NPSN</label>
                      <input type="text" class="form-control form-input-number" name="id" value="">
                      @if($errors->has('id'))
                        <span class="label-error">{{ $errors->first('id') }}</span>
                      @endif
                    </div>
                  </div>
                </div>
              @endif
              @csrf
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group label-floating
                    @if($errors->has('nama'))
                      has-error
                    @endif">
                    <label class="bmd-label-floating">Nama</label>
                    <input type="text" class="form-control" name="nama" value="{{ $school->nama }}">
                    @if($errors->has('nama'))
                      <span class="label-error">{{ $errors->first('nama') }}</span>
                    @endif
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group label-floating
                    @if($errors->has('alamat'))
                      has-error
                    @endif">
                    <label class="bmd-label-floating">Alamat</label>
                    <input type="text" class="form-control" name="alamat" value="{{ $school->alamat }}">
                    @if($errors->has('alamat'))
                      <span class="label-error">{{ $errors->first('alamat') }}</span>
                    @endif
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group label-floating
                    @if($errors->has('status'))
                      has-error
                    @endif">
                    <label class="bmd-label-floating">Status</label>
                    <input type="text" class="form-control" name="status" value="{{ $school->status }}">
                    @if($errors->has('status'))
                      <span class="label-error">{{ $errors->first('status') }}</span>
                    @endif
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group label-floating
                    @if($errors->has('jenjang'))
                      has-error
                    @endif">
                    <label class="bmd-label-floating">Jenjang</label>
                    <input type="text" class="form-control" name="jenjang" value="{{ $school->jenjang }}">
                    @if($errors->has('jenjang'))
                      <span class="label-error">{{ $errors->first('jenjang') }}</span>
                    @endif
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group label-floating
                    @if($errors->has('prestige'))
                      has-error
                    @endif">
                    <label class="bmd-label-floating">Prestige</label>
                    <input type="text" class="form-control form-input-number" name="prestige" value="{{ round($school->prestige) }}">
                    @if($errors->has('prestige'))
                      <span class="label-error">{{ $errors->first('prestige') }}</span>
                    @endif
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group label-floating
                    @if($errors->has('level'))
                      has-error
                    @endif">
                    <label class="bmd-label-floating">Level</label>
                    <input type="text" class="form-control form-input-number" name="level" value="{{ $school->level }}">
                    @if($errors->has('level'))
                      <span class="label-error">{{ $errors->first('level') }}</span>
                    @endif
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group label-floating
                    @if($errors->has('x'))
                      has-error
                    @endif">
                    <label class="bmd-label-floating">Posisi (X)</label>
                    <input type="text" class="form-control form-input-number" name="x" value="{{ $school->x }}">
                    @if($errors->has('x'))
                      <span class="label-error">{{ $errors->first('x') }}</span>
                    @endif
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group label-floating
                    @if($errors->has('y'))
                      has-error
                    @endif">
                    <label class="bmd-label-floating">Posisi (Y)</label>
                    <input type="text" class="form-control form-input-number" name="y" value="{{ $school->y }}">
                    @if($errors->has('y'))
                      <span class="label-error">{{ $errors->first('y') }}</span>
                    @endif
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <label class="bmd-label-floating">Upload Picture: </label>
                  <input type="file" name="picture" class="btn btn-primary" id="form_input_picture">
                </div>
              </div>
              <div class="row">
                <div class="col-md-6">
                  <label class="bmd-label-floating">Foto Lama</label> <br>
                  <img src="{{ $school->getImageAsset() }}" id="form_picture_preview_old" style="width: 100%; height: auto" />
                </div>
                <div class="col-md-6">
                  <label class="bmd-label-floating">Foto Baru</label> <br>
                  <img id="form_picture_preview_new" src="{{ asset('img/no-image.png') }}" style="width: 100%; height: auto" />
                </div>
              </div>
              <button type="submit" class="btn btn-primary pull-right">Save</button>
              <a href="{{ route('schools.index') }}"><button type="button" class="btn btn-secondary pull-right">Cancel</button></a>
              <div class="clearfix"></div>
            </form>
          </div>
        </div>
      </div>

    </div>
  </div>

@endsection

@section('scripts')
  <script type="text/javascript">
    $('#form_input_picture').change(function()
      {
        if (this.files && this.files[0])
        {
          var reader = new FileReader();
          reader.onload = function(e)
          {
              document.getElementById('form_picture_preview_new').src = e.target.result;
          }

          reader.readAsDataURL(this.files[0]);
        }
        else
        {
          document.getElementById('form_picture_preview_new').src='{{ asset('img/no-image.png') }}';
        }
      });
  </script>
@endsection

resources/views/admin/school/list.blade.php
@extends('admin.school.template')

@section('content')
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <div class="card">
            <div class="card-header card-header-primary">
              <h4 class="card-title">
                Schools
                <a class="btn btn-success" style="float: right;" href="{{ route('schools.create') }}">
                  <i class="material-icons">add</i> Add New
                  <div class="ripple-container"></div>
                </a>
              </h4>
              <p class="card-category">Manage schools</p>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table">
                  <thead class=" text-primary">
                    <th>NPSN</th>
                    <th>Nama</th>
                    <th>Alamat</th>
                    <th>J</th>
                    <th>Prestige</th>
                    <th>Level</th>
                    <th>Action</th>
                  </thead>
                  <tbody>
                    @foreach($schools as $row)
                      <tr>
                        <td>{{ $row->id }}</td>
                        <td>{{ $row->nama }}</td>
                        <td>{{ $row->alamat }}</td>
                        <td>{{ $row->jenjang }}</td>
                        <td>{{ round($row->prestige) }}</td>
                        <td>{{ $row->level }}</td>
                        <td>
                          <a href="{{ route('schools.edit', ['id' => $row->id]) }}"><button class="btn-small btn-primary">Edit</button></a>
                          @if($row->isCanBeDeleted())
                            <button class="btn-small btn-danger" onclick="changeToDeleteId({{ $row->id }});" data-toggle="modal" data-target="#modal_delete">Delete</button>
                          @else
                            <button class="btn-small btn-secondary" disabled>Delete</button>
                          @endif
                        </td>
                      </tr>
                    @endforeach
                  </tbody>
                </table>
              </div>
              @include('common.addon_pagination')
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Modal -->
  <div class="modal fade" id="modal_delete" tabindex="-1" role="dialog" aria-labelledby="modal_delete_title" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="modal_delete_title">Delete</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          Are you sure you want to delete this data?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
          <button type="button" class="btn btn-danger" onclick="deleteItem();">Delete</button>
        </div>
      </div>
    </div>
  </div>
@endsection

@section('scripts')
  <script type="text/javascript">
    var toDeleteId = -1;
    function deleteItem()
    {
      var urlFormat = "{{ route('schools.destroy', ['id' => 'VAR_ID']) }}";
      urlFormat = urlFormat.replace('VAR_ID', toDeleteId);
      //alert(urlFormat);
      $.ajax({
        type: "DELETE",
        url: urlFormat,
        headers: { "X-CSRF-TOKEN" : "{{ csrf_token() }}" },
        processData: false,
        contentType: false,
        cache: false,
        timeout: 600000,
        success: function (data)
        {
          varResultObj = JSON.parse(data); // assume the return will always be {"status" : "success"} OR {"status" : "fail"}
          if(varResultObj.status == "success")
          {
            window.location = "{{ route('schools.index') }}";
          }
          else
          {
            alert('ERROR, response: ' + data);
          }
        },
        error: function (e) {
          alert('Cannot delete record, foreign key constraint failed!');
          console.log("ERROR : ", e);
        }
      });
    }
    function changeToDeleteId(newId)
    {
      toDeleteId = newId;
    }
  </script>
@endsection

resources/views/admin/school/template.blade.php
@extends('admin.template')

@section('searchBarAction')
  {{ route('adminSchoolSearchRedirect') }}
@endsection

@section('searchBarVisibility')
  inline-block
@endsection

@section('scriptNav')
  <script type="text/javascript">
    $("#nav_item_schools").addClass("active");
  </script>
@endsection